### ISSUE TITLE
PodDisruptionBudget is policy/v1 in Kubernetes v1.25

### ISSUE THREAD

**Issue by psschwei** [k14s/kapp#620] opened 2022-09-27 13:42 UTC
We use `kapp` in our e2e testing for Knative. When using it on v1.25 Kubernetes clusters, we get a `kapp: Error: Expected to find kind 'policy/v1beta1/PodDisruptionBudget', but did not:` error. 

As the v1beta1 version [has been deprecated](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125), I'd assume that bumping the apiVersion to `policy/v1` [here](https://github.com/vmware-tanzu/carvel-kapp/blob/52a5483c72f03e750df0e9a464dcf15fe52ebbcd/pkg/kapp/config/default.go#L509) would fix the problem.

**Comment by praveenrewar** [comment] 2022-09-27 14:32
Hi @psschwei! Thank you for bringing this to out notice, we definitely need to add `policy/v1` to the pod related matchers that you have specified, but I believe that's not the cause of the error you are getting.
```
kapp: Error: Expected to find kind 'policy/v1beta1/PodDisruptionBudget', but did not:
```
The error indicates that you are trying to deploy a resource of kind `policy/v1beta1/PodDisruptionBudget`, but it was not found on the cluster.

I couldn't find the tests that was failing with this error, but I noticed that on Kubernetes 1.25, `policy/v1/PodDisruptionBudget` is working. (https://github.com/knative/serving/actions/runs/3113577583/jobs/5048488839#step:10:1740)

By any chance are you trying to deploy a previous version of knative serving (which still has `policy/v1beta1/PodDisruptionBudget`) on k8s 1.25?

**Comment by psschwei** [comment] 2022-09-28 19:50
We bumped the PDBs to `v1` at the beginning of the year, and we aren't currently testing any of the versions before the bump. 

cc @skonto for more details on the failing test

**Comment by praveenrewar** [comment] 2022-10-02 19:27
I see. I am not sure what else could cause this issue. @skonto would you be able to share the yaml that was used when you got this error?

**Comment by dprotaso** [comment] 2023-05-25 14:01
Here's a failed run - we don't have v1beta1 anymore so I'm not sure what's triggering kapp to check for that CRD

https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_serving/14003/gateway-api-latest_serving_main/1661690205490384896

**Comment by praveenrewar** [comment] 2023-05-25 14:57
@dprotaso Would you be able to share the manifest so that I can reproduce the issue.

**Comment by dprotaso** [comment] 2023-05-25 15:13
Actually looks like we are using an older version of istio in one scenario that has v1beta1/PDBs

I think we're good to close this issue.

**Closed as completed** 2023-05-25 20:02 UTC
Labels: helping with an issue, discussion
