### ISSUE TITLE
kapp deploy is slow: ChangeGraph step takes 6m36s

### ISSUE THREAD

**Issue by yanniszark** [k14s/kapp#139] opened 2020-08-31 14:10 UTC
Hi all!
I'm in the process of trying out kapp for our use-case. It seems like an awesome tool and towards the right direction!
The way I use kapp is to define all YAML to be applied to the cluster in one huge file and then run:
```bash
kapp deploy --app myinstall -f dump.yaml --debug
```

However, it takes a really long time to get ready to apply.
Specifically, the ChangeGraph step takes too long (6m36s):
```
04:53:52PM: debug: ClusterChangeSet: ChangeGraph: NewChangeGraph: start
04:53:52PM: debug: ClusterChangeSet: ChangeGraph: buildEdges: start
04:58:57PM: debug: ClusterChangeSet: ChangeGraph: buildEdges: end (5m5.715404552s)
04:58:57PM: debug: ClusterChangeSet: ChangeGraph: checkCycles: start
04:58:57PM: debug: ClusterChangeSet: ChangeGraph: checkCycles: end (439.519µs)
04:58:57PM: debug: ClusterChangeSet: ChangeGraph: buildEdges: start
05:00:28PM: debug: ClusterChangeSet: ChangeGraph: buildEdges: end (1m30.522445092s)
05:00:28PM: debug: ClusterChangeSet: ChangeGraph: checkCycles: start
05:00:28PM: debug: ClusterChangeSet: ChangeGraph: checkCycles: end (2.020123ms)
05:00:28PM: debug: ClusterChangeSet: ChangeGraph: NewChangeGraph: end (6m36.250179282s)
```

Is this expected? I'm running a k3s cluster on a 8core VM in GCP.
What is ChangeGraph doing that is taking so long?

**Comment by cppforlife** [comment] 2020-08-31 16:32
hey @yanniszark,

> Is this expected? I'm running a k3s cluster on a 8core VM in GCP.

nope this isnt expected. typically this step takes a few seconds.

cluster size in this case isnt related since kapp is just trying to calculate order of changes to apply. (it builds a tree structure in memory and figures out which changes depend on other changes).

are you using custom ordering rules? if so what are they? also how many resources are in your configuration and what version of kapp are you using.

**Comment by yanniszark** [comment] 2020-08-31 17:57
@cppforlife I'm using the default `kapp`, without any custom ordering rules.
I'm using version `0.33.0` and I am applying 562 resources simultaneously (45159 lines of YAML).
While this may sound like a lot, this is a fairly typical installation.
I'm applying all of those resources as one big application, like so:

```bash
kapp deploy --app myinstall -f dump.yaml --debug
```

> cluster size in this case isnt related since kapp is just trying to calculate order of changes to apply. (it builds a tree structure in memory and figures out which changes depend on other changes).

What is the complexity of this algorithm? Does it depend on fetching things from the cluster?
Maybe the tree doesn't fit in memory and gets swapped out? :thinking:

**Comment by StevenLocke** [comment] 2020-09-01 21:50
That's fascinating, thanks @yanniszark!

We agree that your resources and YAML size seem reasonable, in fact we have a test in our suite which operates on a deployment on the same order of magnitude.[1] We tried deploying the resources defined in those assets locally against a kind cluster, using the same debug flag, and got a significantly quicker graph calculation.

```Shell
kapp deploy --app my-app -f pkg/kapp/diffgraph/assets/cf-for-k8s.yml --debug
...
02:32:40PM: debug: ClusterChangeSet: ChangeGraph: NewChangeGraph: start
02:32:40PM: debug: ClusterChangeSet: ChangeGraph: buildEdges: start
02:32:40PM: debug: ClusterChangeSet: ChangeGraph: buildEdges: end (8.609616ms)
02:32:40PM: debug: ClusterChangeSet: ChangeGraph: checkCycles: start
02:32:40PM: debug: ClusterChangeSet: ChangeGraph: checkCycles: end (111.067µs)
02:32:40PM: debug: ClusterChangeSet: ChangeGraph: buildEdges: start
02:32:40PM: debug: ClusterChangeSet: ChangeGraph: buildEdges: end (9.784575ms)
02:32:40PM: debug: ClusterChangeSet: ChangeGraph: checkCycles: start
02:32:40PM: debug: ClusterChangeSet: ChangeGraph: checkCycles: end (282.644µs)
02:32:40PM: debug: ClusterChangeSet: ChangeGraph: NewChangeGraph: end (20.440511ms)
```

If you try deploying that same cf-for-k8s manifest, what do your timings look like?


[1] That is [TestChangeGraphCFForK8sUpsert](https://github.com/k14s/kapp/blob/1111f860b9f82771d9517432a490c8dc4339b52d/pkg/kapp/diffgraph/change_graph_cf_for_k8s_test.go#L17), using the [cf-for-k8s.yml](https://github.com/k14s/kapp/blob/9d4a1d4a04c4d42a7884a0c4461bb38c227256c6/pkg/kapp/diffgraph/assets/cf-for-k8s.yml)

**Comment by cppforlife** [comment] 2020-09-02 16:20
(per DM discussion with @yanniszark we'll wait for reproducible config.)

**Comment by cppforlife** [comment] 2020-09-25 14:27
closing since we cannot repro. feel free to reopen if new information is available.

**Closed as completed by cppforlife** 2020-09-25 14:27 UTC
Labels: helping with an issue
