### ISSUE TITLE
Deployment with strategy RECREATE doesn't wait for reconciliation during redeploy.

### ISSUE THREAD

**Issue by rohitagg2020** [k14s/kapp#448] opened 2022-02-28 06:32 UTC
**What steps did you take:**
Create a deployment with `strategy: Recreate` and `replicas: 1`. Do the initial `kapp deploy`. Make some changes to deployment. Redeploy with `kapp deploy` again. This time, you will see that it didn't wait for reconciliation. 

For more information, check https://github.com/vmware-tanzu/carvel-kapp/discussions/434

**Comment by rohitagg2020** [comment] 2022-02-28 06:35
cc @ChristianCiach, please add if I have missed anything.

**Comment by ChristianCiach** [comment] 2022-02-28 19:58
One more thing worth mentioning: This issue doesn't happen *always*. It just happens *often*. 

This gist should be helpful to reproduce this issue: https://gist.github.com/ChristianCiach/77bd050b79fae61a71e8cb9b52ddc702

**Comment by ciis0** [comment] 2022-04-08 15:13
<s>maybe linked to this section in code?

https://github.com/vmware-tanzu/carvel-kapp/blob/e0bf1c9d485c5c59a23b4cfe75915782e7fb4b42/pkg/kapp/resourcesmisc/apps_v1_deployment.go#L65-L71
</s>
if the image is not yet pulled, no new replicaset is there yet <s>and it seems like the method runs into the return here https://github.com/vmware-tanzu/carvel-kapp/blob/e0bf1c9d485c5c59a23b4cfe75915782e7fb4b42/pkg/kapp/resourcesmisc/apps_v1_deployment.go#L78
</s>

edit: no, then adding the annotation would not fix it.

**Comment by criztovyl** [comment] 2022-04-09 15:18
I have a funny idea I would like to check:

1. run a local registry
   `docker run -d -p 5000:5000 --restart always --name registry registry:2`
2. put a throttling proxy in front of the registry and make it *terribly* slow:
   <code><a href="">devd</a> /=http&colon;//127.0.0.1:5000/ --tls --up 16 --down 16 --latency 5000</code> (--up/--down in KBs)
3. run minikube
4. create and update a `strategy: Recreate` deployment using kapp there, targeting an image in the throttled registry (with always pulling image)

That should make the "large image" behavior observable. I'll report back with the results.

**Comment by criztovyl** [comment] 2022-04-10 02:01
A reproducible test-case: https://github.com/criztovyl/kapp-448

My observation is that the actual problem does not seem to be the new ReplicaSet but the old one, i could *not* reliably reproduce the issue with the slow/throttled registry. While toying around I then discovered that the time the *old* RS takes to terminate its pods (gracefully) seems to be the actual problem.

Below a table which states the deployment goes through.
(`p` = previous generation, `i` = interims generation (`p+1`), `n` = new generation (`p+2`))

|generation|observedGeneration|unavailableReplicas|updateReplicas|
|-|-|-|-|
|`p`|`p`|`0`|`1`|
|`i`|`p`|`0`|`1`|
|`n`|`p`|`0`|`1`|
|`n`|`n`|`0` :zap:|`0`|
|`n`|`n`|`1`|`0`|
|`n`|`n`|`1`|`1`|
|`n`|`n`|`0`|`1`|

:zap: kapp would wrongly consider this done

for me that looks like the following has a race-condition for n/n/0:
https://github.com/vmware-tanzu/carvel-kapp/blob/e0bf1c9d485c5c59a23b4cfe75915782e7fb4b42/pkg/kapp/resourcesmisc/apps_v1_deployment.go#L73

but it also looks like it can be fixed by also taking into account `.status.updatedReplicas > 0`. :)

**Comment by criztovyl** [comment] 2022-04-10 02:10
this is btw how kubectl seems to check deployment state:

https://github.com/kubernetes/kubectl/blob/652881798563c00c1895ded6ced819030bfaa4d7/pkg/polymorphichelpers/rollout_status.go#L58-L92

**Comment by kumaritanushree** [comment] 2022-04-28 08:51
**Acceptance Criteria:**
> With deploy strategy "RECREATE", KAPP should wait for reconciliation for the operations:
- [x]  Fresh deploy of an application
- [x]  Update in existing deployment (like change image)
- [x]  Increasing number of replicas (scaleUp)
- [x]  Decreasing number of replicas (scaleDown)
- [x]  Delete

> With no deploy strategy, KAPP should wait for reconciliation for the operations:
- [x]  Fresh deploy of an application
- [x]  Update in existing deployment (like change image)
- [x]  Increasing number of replicas (scaleUp)
- [x]  Decreasing number of replicas (scaleDown)
- [x]  Delete

**Closed as completed** 2022-05-05 04:17 UTC
Labels: bug, carvel accepted

**Comment by ciis0** [comment] 2022-05-05 06:25
Is there a plan when the next release that contains this fix will be available?

**Comment by praveenrewar** [comment] 2022-05-05 07:18
@ciis0 We are planning to make a release today (if we are not able to do it today, then probably in a couple of days).

**Comment by ciis0** [comment] 2022-05-05 07:31
ok, then I was just impatient ^^

Thank you!

**Comment by renuy** [comment] 2022-05-05 17:51
Fix available as part of kapp v0.47.0
