### ISSUE TITLE
kapp should work with kubernetes APIs that are affected by faulty APIService resources

### ISSUE THREAD

**Issue by nocquidant** [k14s/kapp#12] opened 2019-05-31 08:05 UTC
Hi,

I've recently played with certmanager and mess up my environment a little bit (my namespaces refused to be deleted so I had to force the deletion). But, since then, I couldn't launch kapp anymore:

```
kapp deploy -n hello -a app-hello -f ./sandbox/config.app.yml                                                                  
Error: unable to retrieve the complete list of server APIs: admission.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request
```

Delete the orphaned apiservices did the trick: `kubectl delete apiservices v1beta1.admission.certmanager.k8s.io`

Could kapp be more resilient here and start even in case of errors in server APIs?

Thanks
--nick

**Comment by cppforlife** [comment] 2019-05-31 10:41
did you install that apiservice resource via kapp as well?

**Comment by nocquidant** [comment] 2019-05-31 13:29
Don't remember if I used helm or not, but it wasn't kapp.

**Comment by cppforlife** [comment] 2019-05-31 14:05
> Could kapp be more resilient here and start even in case of errors in server APIs?

in theory we could try and ignore certain types of resources _if they are not used_; however, i do not know if there repercussions from that down the line (some random controller may fail to create some resource somewhere, etc.)

this seems to be similar to https://github.com/k14s/kapp/issues/8 where someone else also had to bad config in the cluster. ill dig in more to see if there are downsides. cc @nimakaviani may have an opinion.

**Comment by nimakaviani** [comment] 2019-05-31 19:08
My take is similar to the following comment from #8. It is hard to draw the line between which resources to ignore and which ones not to. 

> wouldnt ignoring that error potentially hide some resources? seems like fixing underlying problem is better.

**Comment by cppforlife** [comment] 2019-06-03 19:55
@nocquidant another question for you, do you foresee this problem cropping up in your cluster periodically due to other tools' activity, or it was more of a one off?

**Comment by nocquidant** [comment] 2019-06-04 15:26
It was more of a one off. Feel free to close the issue. Thanks

**Comment by cppforlife** [comment] 2019-06-19 00:18
closing for now. i included issue to this link in the error [1] to lead people here to gather more feedback. please +1 and reopen if issue persists.

[1] https://github.com/k14s/kapp/commit/a6ee5c88df39710458e5f3fe80d868f50eac85bd

**Comment by cppforlife** [comment] 2019-08-16 00:26
reopening since im thinking more about this. someone else just recently reported this in slack: https://kubernetes.slack.com/archives/CH8KCCKA5/p1565900345299800. i've also run into this myself a few days ago with certmgr as well. 

thinking about putting some apiservice ordering constraints that by default would make ux better...

**Comment by cppforlife** [comment] 2019-09-05 21:14
similar issue in #35 related to installing certmanager. replied there as well:

if new APIService is installed and it does not have backing components available, it breaks certain k8s APIs that kapp happens to use (also used by `kubectl api-resources` command).

one way to fix this issue is by making sure that kapp install apiservice backing components before installing APIService itself. to do so one can use kapp ordering directives. ive actually previously installed certmgr this way as shown here: https://github.com/k14s/k8s-resource-protection/tree/develop/config-certmanager. this directory can be installed via `ytt -f . --ignore-unknown-comments | kapp deploy -a certmgr -f- -y`.

https://github.com/k14s/k8s-resource-protection/tree/develop/config-certmanager/patches.yml makes sure that APIService is installed after deployment+service, and deleted first in case of deletion.

**Comment by rochacon** [comment] 2019-09-26 18:26
Adding more notes here, I just had a few issues deploying with kapp during a metric-server outage in my cluster. The application being deployed with kapp was unrelated to metrics-server and did not manage its resources.

The error message pointed my back to this issue.

**Comment by apivzero** [comment] 2019-10-18 13:14
Bump on this, had similar issues as described. This ended up being viewed as "another problems with kubes" by the team prior to understanding that it was just this issue.

**Comment by ahmetb** [comment] 2019-12-22 00:33
ditto, ran into this via

```
Error: unable to retrieve the complete list of server APIs: 
custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```

**Comment by rochacon** [comment] 2019-12-22 18:57
Have you tried running with kapp v0.15.0+ and `--dangerous-ignore-failing-api-services` flag?
This seems to help with the issue, but is not enabled by default.

**Comment by cppforlife** [comment] 2020-01-24 05:32
behaviour significantly improved in https://github.com/k14s/kapp/commit/08a889be4cff53c5bc6740a79b929c1c01ca1fb0. implemented to ignore specific failing api services _if_ they do not directly relate to application deployed by tracking its group versions. if any resources are within failing api groups kapp will still return error (but based on whats ive seen people deploy it's not a common case.) will be available in upcoming release.

**Comment by cppforlife** [comment] 2020-01-24 23:54
improvement is available in https://github.com/k14s/kapp/releases/tag/v0.18.0.

**Closed by cppforlife** 2020-01-24 23:54 UTC
Labels: discussion, enhancement, helping-with-an-issue

**Comment by pavel-khritonenko** [comment] 2020-05-22 07:00
Updated my cluster to 1.16 (EKS), and start facing these errors:

```
Error: unable to retrieve the complete list of server APIs: mutators.kubedb.com/v1alpha1: the server is currently unable to handle the request, validators.kubedb.com/v1alpha1: the server is currently unable to handle the request (possibly related issue: https://github.com/k14s/kapp/issues/12)
```

All APIServices are good:

```
$ k get apiservices
NAME                                   SERVICE                       AVAILABLE   AGE
v1.                                    Local                         True        520d
v1.admissionregistration.k8s.io        Local                         True        13h
v1.apiextensions.k8s.io                Local                         True        13h
v1.apps                                Local                         True        520d
v1.authentication.k8s.io               Local                         True        520d
v1.authorization.k8s.io                Local                         True        520d
v1.autoscaling                         Local                         True        520d
v1.batch                               Local                         True        520d
v1.coordination.k8s.io                 Local                         True        238d
v1.databases.spotahome.com             Local                         True        13h
v1.jaegertracing.io                    Local                         True        13h
v1.monitoring.coreos.com               Local                         True        13h
v1.networking.k8s.io                   Local                         True        520d
v1.rbac.authorization.k8s.io           Local                         True        520d
v1.scheduling.k8s.io                   Local                         True        238d
v1.storage.k8s.io                      Local                         True        520d
v1alpha1.appcatalog.appscode.com       Local                         True        13h
v1alpha1.catalog.kubedb.com            Local                         True        13h
v1alpha1.certmanager.k8s.io            Local                         True        13h
v1alpha1.crd.k8s.amazonaws.com         Local                         True        13h
v1alpha1.kubedb.com                    Local                         True        13h
v1alpha1.mutators.kubedb.com           kube-system/kubedb-operator   True        374d
v1alpha1.validators.kubedb.com         kube-system/kubedb-operator   True        374d
v1alpha2.acme.cert-manager.io          Local                         True        13h
v1alpha2.cert-manager.io               Local                         True        13h
v1alpha2.storage.spotahome.com         Local                         True        13h
v1beta1.admissionregistration.k8s.io   Local                         True        520d
v1beta1.apiextensions.k8s.io           Local                         True        520d
v1beta1.authentication.k8s.io          Local                         True        520d
v1beta1.authorization.k8s.io           Local                         True        520d
v1beta1.batch                          Local                         True        520d
v1beta1.certificates.k8s.io            Local                         True        520d
v1beta1.coordination.k8s.io            Local                         True        357d
v1beta1.events.k8s.io                  Local                         True        520d
v1beta1.extensions                     Local                         True        520d
v1beta1.metrics.k8s.io                 kube-system/metrics-server    True        406d
v1beta1.networking.k8s.io              Local                         True        238d
v1beta1.node.k8s.io                    Local                         True        238d
v1beta1.policy                         Local                         True        520d
v1beta1.rbac.authorization.k8s.io      Local                         True        520d
v1beta1.scheduling.k8s.io              Local                         True        493d
v1beta1.storage.k8s.io                 Local                         True        520d
v2beta1.autoscaling                    Local                         True        520d
v2beta2.autoscaling                    Local                         True        357d
```

kapp version v0.13.0, just for history and for enable googling such issues, trying to upgrade to 0.18

**Comment by soumyapanigrahi-code** [comment] 2021-08-25 02:37
I am able to reproduce this issue consistently on kapp version 0.23.0, here are the findings:

1. packaging-api  service exists in tanzu-system namespace as expected.
`NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
packaging-api   ClusterIP   10.19.250.254   <none>        443/TCP   22m`

2. v1alpha1.data.packaging.carvel.dev api-service instance is correctly pointing to packaging-api in tanzu-system
`v1alpha1.data.packaging.carvel.dev   tanzu-system/packaging-api   True        19m`

3. packaging-api  endpoint correctly resolves to the kapp-controller pod IP in tanzu-system namespace
`1.  packaging-api   10.16.1.7:10350   24m`
`2. kapp-controller-f765549c5-gt8kk   1/1     Running   0          27m   10.16.1.7   gke-xxxxxxx-xxxxx-210-default-pool-c00197c5-x4fc   <none>           <none>`

4. However the Package Repository status remains unchanged and the repo contents remain undiscovered forever with the following message:
`Updated At:          2021-08-24T17:18:12Z
  Useful Error Message:  kapp: Error: unable to retrieve the complete list of server APIs: data.packaging.carvel.dev/v1alpha1: the server is currently unable to handle the request (possibly related issue: https://github.com/vmware-tanzu/carvel-kapp/issues/12)`

5. Additional debug information on the error:
`0825 09:04:57.398210   29937 round_trippers.go:457] Response Status: 503 Service Unavailable in 1000 milliseconds
I0825 09:04:57.827450   29937 request.go:1347] body was not decodable (unable to check for Status): yaml: mapping values are not allowed in this context
I0825 09:04:57.827508   29937 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request
I0825 09:04:57.832371   29937 round_trippers.go:432] GET https://35.243.224.19/apis/data.packaging.carvel.dev/v1alpha1?timeout=32s
I0825 09:04:57.832403   29937 round_trippers.go:438] Request Headers:
I0825 09:04:57.832416   29937 round_trippers.go:442]     User-Agent: kubectl/v1.21.2 (darwin/amd64) kubernetes/092fbfb
I0825 09:04:57.832425   29937 round_trippers.go:442]     Accept: application/json, */*
I0825 09:04:58.150319   29937 round_trippers.go:457] Response Status: 503 Service Unavailable in 317 milliseconds
I0825 09:04:58.166684   29937 request.go:1347] body was not decodable (unable to check for Status): yaml: mapping values are not allowed in this context
I0825 09:04:58.166710   29937 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request
I0825 09:04:58.166759   29937 shortcut.go:89] Error loading discovery information: unable to retrieve the complete list of server APIs: data.packaging.carvel.dev/v1alpha1: the server is currently unable to handle the request`

**Comment by Turbots** [comment] 2022-06-14 22:34
Getting the same error when installing TAP on EKS using `tanzu` CLI... so cannot control what kapp does...

`kapp` version `0.42.0`
`kubectl` version `1.22.10`
`tanzu` version `0.11.1`

**Comment by 100mik** [comment] 2022-06-16 06:06
Hey @Turbots !
Could you share the entire error message? Also, is this error recurring?
The version of kapp-controller running on your cluster will help out as well!

**Comment by mdzhigarov** [comment] 2026-04-06 07:22
Still reproducing this occasionally with KC v0.59.3 and Kapp v0.65.1.
We're upgrading cert manager, local path provisioner and KC one after another and then try to upgrade out PackageRepository:

```
2026-04-03 19:20:51 [INFO] Deploy kapp-controller ...  
           Target cluster 'https://master.cfcr.internal:8443/' (nodes: 88.0.0.17, 9+)  
             
           Changes  
             
           Namespace        Name             Kind        Age  Op      Op st.  Wait to    Rs  Ri    
           kapp-controller  kapp-controller  Deployment  6h   update  -       reconcile  ok  -    
             
           Op:      0 create, 0 delete, 1 update, 0 noop, 0 exists  
           Wait to: 1 reconcile, 0 delete, 0 noop  
             
           7:20:52PM: ---- applying 1 changes [0/1 done] ----  
           7:20:52PM: update deployment/kapp-controller (apps/v1) namespace: kapp-controller  
           7:20:52PM: ---- waiting on 1 changes [0/1 done] ----  
           7:20:52PM: ongoing: reconcile deployment/kapp-controller (apps/v1) namespace: kapp-controller  
           7:20:52PM:  ^ Waiting for generation 4 to be observed  
           7:20:52PM:  L ok: waiting on replicaset/kapp-controller-759b67894c (apps/v1) namespace: kapp-controller  
           7:20:52PM:  L ok: waiting on replicaset/kapp-controller-65b8b5db75 (apps/v1) namespace: kapp-controller  
           7:20:52PM:  L ok: waiting on pod/kapp-controller-759b67894c-777n8 (v1) namespace: kapp-controller  
           7:20:52PM:  L ongoing: waiting on pod/kapp-controller-65b8b5db75-jb6st (v1) namespace: kapp-controller  
           7:20:52PM:     ^ Pending  
           7:20:55PM: ongoing: reconcile deployment/kapp-controller (apps/v1) namespace: kapp-controller  
           7:20:55PM:  ^ Waiting for 1 unavailable replicas  
           7:20:55PM:  L ok: waiting on replicaset/kapp-controller-759b67894c (apps/v1) namespace: kapp-controller  
           7:20:55PM:  L ok: waiting on replicaset/kapp-controller-65b8b5db75 (apps/v1) namespace: kapp-controller  
           7:20:55PM:  L ok: waiting on pod/kapp-controller-759b67894c-777n8 (v1) namespace: kapp-controller  
           7:20:55PM:  L ongoing: waiting on pod/kapp-controller-65b8b5db75-jb6st (v1) namespace: kapp-controller  
           7:20:55PM:     ^ Pending: ContainerCreating  
           7:21:01PM: ok: reconcile deployment/kapp-controller (apps/v1) namespace: kapp-controller  
           7:21:01PM: ---- applying complete [1/1 done] ----  
           7:21:01PM: ---- waiting complete [1/1 done] ----  
             
           Succeeded  
           2026-04-03 19:21:01 [INFO] Installing cert-manager ...  
           2026-04-03 19:21:02 [INFO] Deploy cert-manager ...  
           Target cluster 'https://master.cfcr.internal:8443/' (nodes: 88.0.0.17, 9+)  
             
           Changes  
             
           Namespace     Name                     Kind        Age  Op      Op st.  Wait to    Rs  Ri    
           cert-manager  cert-manager             Deployment  6h   update  -       reconcile  ok  -    
           ^             cert-manager-cainjector  Deployment  6h   update  -       reconcile  ok  -    
           ^             cert-manager-webhook     Deployment  6h   update  -       reconcile  ok  -    
             
           Op:      0 create, 0 delete, 3 update, 0 noop, 0 exists  
           Wait to: 3 reconcile, 0 delete, 0 noop  
             
           7:21:03PM: ---- applying 3 changes [0/3 done] ----  
           7:21:03PM: update deployment/cert-manager (apps/v1) namespace: cert-manager  
           7:21:03PM: update deployment/cert-manager-webhook (apps/v1) namespace: cert-manager  
           7:21:09PM:  L ongoing: waiting on pod/cert-manager-webhook-6f74976f4-x7shp (v1) namespace: cert-manager  
           7:21:09PM:     ^ Condition Ready is not True (False)  
           7:21:09PM:  L ok: waiting on pod/cert-manager-webhook-6d96f5db86-zcz2r (v1) namespace: cert-manager  
           7:21:09PM: ---- waiting on 1 changes [2/3 done] ----  
           7:21:15PM: ok: reconcile deployment/cert-manager-webhook (apps/v1) namespace: cert-manager  
           7:21:15PM: ---- applying complete [3/3 done] ----  
           7:21:15PM: ---- waiting complete [3/3 done] ----  
             
           Succeeded  
           2026-04-03 19:21:15 [INFO] Installing secretgen-controller ...  
           2026-04-03 19:21:15 [INFO] Deploy secretgen-controller ...  
           Target cluster 'https://master.cfcr.internal:8443/' (nodes: 88.0.0.17, 9+)  
             
           Changes  
             
           Namespace  Name  Kind  Age  Op  Op st.  Wait to  Rs  Ri    
             
           Op:      0 create, 0 delete, 0 update, 0 noop, 0 exists  
           Wait to: 0 reconcile, 0 delete, 0 noop  
             
           Succeeded  
           2026-04-03 19:21:15 [INFO] Installing storage plugin ...  
           2026-04-03 19:21:15 [INFO] Deploying storage plugin ...  
           Target cluster 'https://master.cfcr.internal:8443/' (nodes: 88.0.0.17, 9+)  
             
           Changes  
             
           Namespace           Name                    Kind        Age  Op      Op st.  Wait to    Rs  Ri    
           local-path-storage  local-path-config       ConfigMap   6h   update  -       reconcile  ok  -    
           ^                   local-path-provisioner  Deployment  6h   update  -       reconcile  ok  -    
             
           Op:      0 create, 0 delete, 2 update, 0 noop, 0 exists  
           Wait to: 2 reconcile, 0 delete, 0 noop  
             
           7:21:16PM: ---- applying 1 changes [0/2 done] ----  
           7:21:16PM: update configmap/local-path-config (v1) namespace: local-path-storage  
           7:21:16PM: ---- waiting on 1 changes [0/2 done] ----  
           7:21:16PM: ok: reconcile configmap/local-path-config (v1) namespace: local-path-storage  
           7:21:16PM: ---- applying 1 changes [1/2 done] ----  
           7:21:16PM: update deployment/local-path-provisioner (apps/v1) namespace: local-path-storage  
           7:21:16PM: ---- waiting on 1 changes [1/2 done] ----  
           7:21:16PM: ongoing: reconcile deployment/local-path-provisioner (apps/v1) namespace: local-path-storage  
           7:21:16PM:  ^ Waiting for generation 4 to be observed  
           7:21:16PM:  L ok: waiting on replicaset/local-path-provisioner-899b7fbbf (apps/v1) namespace: local-path-storage  
           7:21:16PM:  L ok: waiting on replicaset/local-path-provisioner-6b6b68c755 (apps/v1) namespace: local-path-storage  
           7:21:16PM:  L ok: waiting on pod/local-path-provisioner-899b7fbbf-jqhwv (v1) namespace: local-path-storage  
           7:21:16PM:  L ongoing: waiting on pod/local-path-provisioner-6b6b68c755-s5kfd (v1) namespace: local-path-storage  
           7:21:16PM:     ^ Pending: ContainerCreating  
           7:21:19PM: ongoing: reconcile deployment/local-path-provisioner (apps/v1) namespace: local-path-storage  
           7:21:19PM:  ^ Waiting for 1 unavailable replicas  
           7:21:19PM:  L ok: waiting on replicaset/local-path-provisioner-899b7fbbf (apps/v1) namespace: local-path-storage  
           7:21:19PM:  L ok: waiting on replicaset/local-path-provisioner-6b6b68c755 (apps/v1) namespace: local-path-storage  
           7:21:19PM:  L ok: waiting on pod/local-path-provisioner-899b7fbbf-jqhwv (v1) namespace: local-path-storage  
           7:21:19PM:  L ongoing: waiting on pod/local-path-provisioner-6b6b68c755-s5kfd (v1) namespace: local-path-storage  
           7:21:19PM:     ^ Pending: ContainerCreating  
           7:21:22PM: ok: reconcile deployment/local-path-provisioner (apps/v1) namespace: local-path-storage  
           7:21:22PM: ---- applying complete [2/2 done] ----  
           7:21:22PM: ---- waiting complete [2/2 done] ---
```


... and then couple of seconds later:

```
[i] Updating Carvel PackageRepository  
           Target cluster 'https://master.cfcr.internal:8443/' (nodes: 88.0.0.17, 9+)  
             
           7:21:31PM: Updating package repository resource 'tanzu.vmware.com' in namespace 'tanzusm'  
           7:21:31PM: Waiting for package repository reconciliation for 'tanzu.vmware.com'  
           7:21:33PM: Fetching   
               | apiVersion: vendir.k14s.io/v1alpha1  
               | directories:  
               | - contents:  
               |   - imgpkgBundle:  
               |       image: registry.internal:10500/hub-self-managed/repo@sha256:50d5d0ab2df3e289811fd3b6be2c9fc1fa8e41aaecf0ded8824827a6b6420527  
               |       tag: 10.4.0-8643-doppler--v8a8bbb7  
               |     path: .  
               |   path: "0"  
               | kind: LockConfig  
               |   
           7:21:33PM: Fetch succeeded   
           7:21:35PM: Template succeeded   
           7:21:35PM: Deploy started (11s ago)  
           7:21:45PM: Deploy failed (1s ago)  
               | kapp: Error: unable to retrieve the complete list of server APIs: data.packaging.carvel.dev/v1alpha1: stale GroupVersion discovery: data.packaging.carvel.dev/v1alpha1 (possibly related issue: https://github.com/carvel-dev/kapp/issues/12)  
               | Deploying: Error (see .status.usefulErrorMessage for details)
```
