### ISSUE TITLE
Deploy with ConfigMap fails when it has the same name with the app - disallowed label 'kapp.k14s.io/is-app'

### ISSUE THREAD

**Issue by georgevad** [k14s/kapp#474] opened 2022-04-06 20:38 UTC
**What steps did you take:**
Tried to deploy this example https://github.com/vmware-tanzu/carvel-kapp/blob/develop/examples/simple-app-example/config-2.yml

Ran : `kapp deploy -a simple-app -f examples/simple-app-example/config-2.yml`

**What happened:**
Received the following error:
```
kapp: Error: Disallowed labels errors:
- Resource 'configmap/simple-app (v1) namespace: default' has a disallowed label 'kapp.k14s.io/is-app'
```

**What did you expect:**
I would expect the application deployed successfully.

**Anything else you would like to add:**
If the app name is changed or the ConfigMap name is changed then it works (the point is that they should be different, otherwise it won't work)

**Environment:**

- kapp version (use `kapp --version`):
```
kapp --version
kapp version 0.46.0

Succeeded
```
- OS (e.g. from `/etc/os-release`): macOS Monterey, Version 12.3.1
- Kubernetes version (use `kubectl version`)
```
kubectl version  
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.6-3+7e02437f65494f", GitCommit:"7e02437f65494f7bd0fd255e6996ce6c773993cf", GitTreeState:"clean", BuildDate:"2022-01-26T22:09:00Z", GoVersion:"go1.16.13", Compiler:"gc", Platform:"linux/arm64"}
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by praveenrewar** [comment] 2022-04-07 05:26
Duplicate of #146.
[PR](https://github.com/vmware-tanzu/carvel-kapp/pull/403) has been merged with a fix and hopefully this will be present in the next release (i.e. v0.47.0)

**Closed as completed by praveenrewar** 2022-04-07 05:26 UTC
Labels: bug
